/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './composables/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
    // Include Nuxt layer files so Tailwind sees classes used there
    './layers/**/*.{vue,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'rgb(var(--color-primary-500) / <alpha-value>)',
          50: 'rgb(var(--color-primary-50) / <alpha-value>)',
          100: 'rgb(var(--color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900) / <alpha-value>)',
          950: 'rgb(var(--color-primary-950) / <alpha-value>)',
        },
        pear: {
          DEFAULT: 'rgb(var(--color-pear-500) / <alpha-value>)',
          50: 'rgb(var(--color-pear-50) / <alpha-value>)',
          100: 'rgb(var(--color-pear-100) / <alpha-value>)',
          200: 'rgb(var(--color-pear-200) / <alpha-value>)',
          300: 'rgb(var(--color-pear-300) / <alpha-value>)',
          400: 'rgb(var(--color-pear-400) / <alpha-value>)',
          500: 'rgb(var(--color-pear-500) / <alpha-value>)',
          600: 'rgb(var(--color-pear-600) / <alpha-value>)',
          700: 'rgb(var(--color-pear-700) / <alpha-value>)',
          800: 'rgb(var(--color-pear-800) / <alpha-value>)',
          900: 'rgb(var(--color-pear-900) / <alpha-value>)',
          950: 'rgb(var(--color-pear-950) / <alpha-value>)',
        },
        green: {
          DEFAULT: 'rgb(var(--color-green-500) / <alpha-value>)',
          50: 'rgb(var(--color-green-50) / <alpha-value>)',
          100: 'rgb(var(--color-green-100) / <alpha-value>)',
          200: 'rgb(var(--color-green-200) / <alpha-value>)',
          300: 'rgb(var(--color-green-300) / <alpha-value>)',
          400: 'rgb(var(--color-green-400) / <alpha-value>)',
          500: 'rgb(var(--color-green-500) / <alpha-value>)',
          600: 'rgb(var(--color-green-600) / <alpha-value>)',
          700: 'rgb(var(--color-green-700) / <alpha-value>)',
          800: 'rgb(var(--color-green-800) / <alpha-value>)',
          900: 'rgb(var(--color-green-900) / <alpha-value>)',
          950: 'rgb(var(--color-green-950) / <alpha-value>)',
        },
        mercury: {
          DEFAULT: 'rgb(var(--color-mercury-500) / <alpha-value>)',
          50: 'rgb(var(--color-mercury-50) / <alpha-value>)',
          100: 'rgb(var(--color-mercury-100) / <alpha-value>)',
          200: 'rgb(var(--color-mercury-200) / <alpha-value>)',
          300: 'rgb(var(--color-mercury-300) / <alpha-value>)',
          400: 'rgb(var(--color-mercury-400) / <alpha-value>)',
          500: 'rgb(var(--color-mercury-500) / <alpha-value>)',
          600: 'rgb(var(--color-mercury-600) / <alpha-value>)',
          700: 'rgb(var(--color-mercury-700) / <alpha-value>)',
          800: 'rgb(var(--color-mercury-800) / <alpha-value>)',
          900: 'rgb(var(--color-mercury-900) / <alpha-value>)',
          950: 'rgb(var(--color-mercury-950) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary-500) / <alpha-value>)',
          50: 'rgb(var(--color-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--color-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--color-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--color-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--color-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--color-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--color-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--color-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--color-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--color-secondary-900) / <alpha-value>)',
          950: 'rgb(var(--color-secondary-950) / <alpha-value>)',
        },
        blue: {
          DEFAULT: 'rgb(var(--color-blue-500) / <alpha-value>)',
          50: 'rgb(var(--color-blue-50) / <alpha-value>)',
          100: 'rgb(var(--color-blue-100) / <alpha-value>)',
          200: 'rgb(var(--color-blue-200) / <alpha-value>)',
          300: 'rgb(var(--color-blue-300) / <alpha-value>)',
          400: 'rgb(var(--color-blue-400) / <alpha-value>)',
          500: 'rgb(var(--color-blue-500) / <alpha-value>)',
          600: 'rgb(var(--color-blue-600) / <alpha-value>)',
          700: 'rgb(var(--color-blue-700) / <alpha-value>)',
          800: 'rgb(var(--color-blue-800) / <alpha-value>)',
          900: 'rgb(var(--color-blue-900) / <alpha-value>)',
          950: 'rgb(var(--color-blue-950) / <alpha-value>)',
        },
        surface: {
          ground: 'var(--surface-ground)',
          section: 'var(--surface-section)',
          card: 'var(--surface-card)',
          overlay: 'var(--surface-overlay)',
          border: 'var(--surface-border)',
          hover: 'var(--surface-hover)',
          color: 'var(--text-color)',
          'secondary-color': 'var(--text-secondary-color)',
          disabled: 'var(--text-disabled)',
          placeholder: 'var(--text-placeholder)',
        },
      },

      borderColor: {
        DEFAULT: 'var(--surface-border)', // Light mode border color
      },
      fontFamily: {
        sans: ['Inter'],
        roboto: ['Roboto'],
        inter: ['Inter'],
      },
      container: {
        center: true,
        padding: '1rem',
      },
      maxWidth: {
        '1/4': '25%',
        '1/2': '50%',
        '3/4': '75%',
      },
      strokeWidth: {
        0.5: 0.5,
        1.5: 1.5,
        2.5: 2.5,
      },
      screens: {
        lgxl: '1150px',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}
